<?xml version="1.0" encoding="utf-8"?><Database Name="CharacterDB" Class="CharacterDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\CharacterDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CharacterDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CharacterTable" Member="CharacterTables">
    <Type Name="CharacterTable">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Occupation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>