//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FinalDBModel", "FK_Package_Software_Package_Software", "Work_Package", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinalProject.Models.Work_Package), "Package_Software", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinalProject.Models.Package_Software), true)]
[assembly: EdmRelationshipAttribute("FinalDBModel", "FK_Package_Software_Software_Requirement", "Software_Requirement", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FinalProject.Models.Software_Requirement), "Package_Software", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FinalProject.Models.Package_Software), true)]

#endregion

namespace FinalProject.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FinalDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FinalDBEntities object using the connection string found in the 'FinalDBEntities' section of the application configuration file.
        /// </summary>
        public FinalDBEntities() : base("name=FinalDBEntities", "FinalDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FinalDBEntities object.
        /// </summary>
        public FinalDBEntities(string connectionString) : base(connectionString, "FinalDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FinalDBEntities object.
        /// </summary>
        public FinalDBEntities(EntityConnection connection) : base(connection, "FinalDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Package_Software> Package_Software
        {
            get
            {
                if ((_Package_Software == null))
                {
                    _Package_Software = base.CreateObjectSet<Package_Software>("Package_Software");
                }
                return _Package_Software;
            }
        }
        private ObjectSet<Package_Software> _Package_Software;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Software_Requirement> Software_Requirement
        {
            get
            {
                if ((_Software_Requirement == null))
                {
                    _Software_Requirement = base.CreateObjectSet<Software_Requirement>("Software_Requirement");
                }
                return _Software_Requirement;
            }
        }
        private ObjectSet<Software_Requirement> _Software_Requirement;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Work_Package> Work_Package
        {
            get
            {
                if ((_Work_Package == null))
                {
                    _Work_Package = base.CreateObjectSet<Work_Package>("Work_Package");
                }
                return _Work_Package;
            }
        }
        private ObjectSet<Work_Package> _Work_Package;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Package_Software EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPackage_Software(Package_Software package_Software)
        {
            base.AddObject("Package_Software", package_Software);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Software_Requirement EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSoftware_Requirement(Software_Requirement software_Requirement)
        {
            base.AddObject("Software_Requirement", software_Requirement);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Work_Package EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWork_Package(Work_Package work_Package)
        {
            base.AddObject("Work_Package", work_Package);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinalDBModel", Name="Package_Software")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Package_Software : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Package_Software object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="wp_id">Initial value of the wp_id property.</param>
        /// <param name="sr_id">Initial value of the sr_id property.</param>
        /// <param name="createddate">Initial value of the createddate property.</param>
        public static Package_Software CreatePackage_Software(global::System.Int32 id, global::System.Int32 wp_id, global::System.Int32 sr_id, global::System.DateTime createddate)
        {
            Package_Software package_Software = new Package_Software();
            package_Software.id = id;
            package_Software.wp_id = wp_id;
            package_Software.sr_id = sr_id;
            package_Software.createddate = createddate;
            return package_Software;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wp_id
        {
            get
            {
                return _wp_id;
            }
            set
            {
                Onwp_idChanging(value);
                ReportPropertyChanging("wp_id");
                _wp_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wp_id");
                Onwp_idChanged();
            }
        }
        private global::System.Int32 _wp_id;
        partial void Onwp_idChanging(global::System.Int32 value);
        partial void Onwp_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sr_id
        {
            get
            {
                return _sr_id;
            }
            set
            {
                Onsr_idChanging(value);
                ReportPropertyChanging("sr_id");
                _sr_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sr_id");
                Onsr_idChanged();
            }
        }
        private global::System.Int32 _sr_id;
        partial void Onsr_idChanging(global::System.Int32 value);
        partial void Onsr_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createddate
        {
            get
            {
                return _createddate;
            }
            set
            {
                OncreateddateChanging(value);
                ReportPropertyChanging("createddate");
                _createddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createddate");
                OncreateddateChanged();
            }
        }
        private global::System.DateTime _createddate;
        partial void OncreateddateChanging(global::System.DateTime value);
        partial void OncreateddateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinalDBModel", "FK_Package_Software_Package_Software", "Work_Package")]
        public Work_Package Work_Package
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Work_Package>("FinalDBModel.FK_Package_Software_Package_Software", "Work_Package").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Work_Package>("FinalDBModel.FK_Package_Software_Package_Software", "Work_Package").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Work_Package> Work_PackageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Work_Package>("FinalDBModel.FK_Package_Software_Package_Software", "Work_Package");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Work_Package>("FinalDBModel.FK_Package_Software_Package_Software", "Work_Package", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinalDBModel", "FK_Package_Software_Software_Requirement", "Software_Requirement")]
        public Software_Requirement Software_Requirement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software_Requirement>("FinalDBModel.FK_Package_Software_Software_Requirement", "Software_Requirement").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software_Requirement>("FinalDBModel.FK_Package_Software_Software_Requirement", "Software_Requirement").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Software_Requirement> Software_RequirementReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Software_Requirement>("FinalDBModel.FK_Package_Software_Software_Requirement", "Software_Requirement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Software_Requirement>("FinalDBModel.FK_Package_Software_Software_Requirement", "Software_Requirement", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinalDBModel", Name="Software_Requirement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Software_Requirement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Software_Requirement object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="createddate">Initial value of the createddate property.</param>
        /// <param name="platform">Initial value of the platform property.</param>
        public static Software_Requirement CreateSoftware_Requirement(global::System.Int32 id, global::System.String title, global::System.DateTime createddate, global::System.String platform)
        {
            Software_Requirement software_Requirement = new Software_Requirement();
            software_Requirement.id = id;
            software_Requirement.title = title;
            software_Requirement.createddate = createddate;
            software_Requirement.platform = platform;
            return software_Requirement;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createddate
        {
            get
            {
                return _createddate;
            }
            set
            {
                OncreateddateChanging(value);
                ReportPropertyChanging("createddate");
                _createddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createddate");
                OncreateddateChanged();
            }
        }
        private global::System.DateTime _createddate;
        partial void OncreateddateChanging(global::System.DateTime value);
        partial void OncreateddateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String platform
        {
            get
            {
                return _platform;
            }
            set
            {
                OnplatformChanging(value);
                ReportPropertyChanging("platform");
                _platform = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("platform");
                OnplatformChanged();
            }
        }
        private global::System.String _platform;
        partial void OnplatformChanging(global::System.String value);
        partial void OnplatformChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinalDBModel", "FK_Package_Software_Software_Requirement", "Package_Software")]
        public EntityCollection<Package_Software> Package_Software
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Package_Software>("FinalDBModel.FK_Package_Software_Software_Requirement", "Package_Software");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Package_Software>("FinalDBModel.FK_Package_Software_Software_Requirement", "Package_Software", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FinalDBModel", Name="Work_Package")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Work_Package : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Work_Package object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="task_id">Initial value of the task_id property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="workorder">Initial value of the workorder property.</param>
        /// <param name="createddate">Initial value of the createddate property.</param>
        public static Work_Package CreateWork_Package(global::System.Int32 id, global::System.String name, global::System.Int32 task_id, global::System.Int16 status, global::System.Int32 workorder, global::System.DateTime createddate)
        {
            Work_Package work_Package = new Work_Package();
            work_Package.id = id;
            work_Package.name = name;
            work_Package.task_id = task_id;
            work_Package.status = status;
            work_Package.workorder = workorder;
            work_Package.createddate = createddate;
            return work_Package;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 task_id
        {
            get
            {
                return _task_id;
            }
            set
            {
                Ontask_idChanging(value);
                ReportPropertyChanging("task_id");
                _task_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("task_id");
                Ontask_idChanged();
            }
        }
        private global::System.Int32 _task_id;
        partial void Ontask_idChanging(global::System.Int32 value);
        partial void Ontask_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int16 _status;
        partial void OnstatusChanging(global::System.Int16 value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 workorder
        {
            get
            {
                return _workorder;
            }
            set
            {
                OnworkorderChanging(value);
                ReportPropertyChanging("workorder");
                _workorder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("workorder");
                OnworkorderChanged();
            }
        }
        private global::System.Int32 _workorder;
        partial void OnworkorderChanging(global::System.Int32 value);
        partial void OnworkorderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createddate
        {
            get
            {
                return _createddate;
            }
            set
            {
                OncreateddateChanging(value);
                ReportPropertyChanging("createddate");
                _createddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createddate");
                OncreateddateChanged();
            }
        }
        private global::System.DateTime _createddate;
        partial void OncreateddateChanging(global::System.DateTime value);
        partial void OncreateddateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FinalDBModel", "FK_Package_Software_Package_Software", "Package_Software")]
        public EntityCollection<Package_Software> Package_Software
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Package_Software>("FinalDBModel.FK_Package_Software_Package_Software", "Package_Software");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Package_Software>("FinalDBModel.FK_Package_Software_Package_Software", "Package_Software", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
