#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FINALDB.MDF")]
	public partial class IPFinalDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPackage_Software(Package_Software instance);
    partial void UpdatePackage_Software(Package_Software instance);
    partial void DeletePackage_Software(Package_Software instance);
    partial void InsertSoftware_Requirement(Software_Requirement instance);
    partial void UpdateSoftware_Requirement(Software_Requirement instance);
    partial void DeleteSoftware_Requirement(Software_Requirement instance);
    partial void InsertWork_Package(Work_Package instance);
    partial void UpdateWork_Package(Work_Package instance);
    partial void DeleteWork_Package(Work_Package instance);
    #endregion
		
		public IPFinalDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FinalDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IPFinalDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPFinalDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPFinalDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPFinalDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Package_Software> Package_Softwares
		{
			get
			{
				return this.GetTable<Package_Software>();
			}
		}
		
		public System.Data.Linq.Table<Software_Requirement> Software_Requirements
		{
			get
			{
				return this.GetTable<Software_Requirement>();
			}
		}
		
		public System.Data.Linq.Table<Work_Package> Work_Packages
		{
			get
			{
				return this.GetTable<Work_Package>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeletePackageSoftware")]
		public int DeletePackageSoftware([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> wpID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), wpID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectedPakcages")]
		public ISingleResult<SelectedPakcagesResult> SelectedPakcages([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> wpID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), wpID);
			return ((ISingleResult<SelectedPakcagesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Package_Software")]
	public partial class Package_Software : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _wp_id;
		
		private int _sr_id;
		
		private System.DateTime _createddate;
		
		private EntityRef<Software_Requirement> _Software_Requirement;
		
		private EntityRef<Work_Package> _Work_Package;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onwp_idChanging(int value);
    partial void Onwp_idChanged();
    partial void Onsr_idChanging(int value);
    partial void Onsr_idChanged();
    partial void OncreateddateChanging(System.DateTime value);
    partial void OncreateddateChanged();
    #endregion
		
		public Package_Software()
		{
			this._Software_Requirement = default(EntityRef<Software_Requirement>);
			this._Work_Package = default(EntityRef<Work_Package>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wp_id", DbType="Int NOT NULL")]
		public int wp_id
		{
			get
			{
				return this._wp_id;
			}
			set
			{
				if ((this._wp_id != value))
				{
					if (this._Work_Package.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onwp_idChanging(value);
					this.SendPropertyChanging();
					this._wp_id = value;
					this.SendPropertyChanged("wp_id");
					this.Onwp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sr_id", DbType="Int NOT NULL")]
		public int sr_id
		{
			get
			{
				return this._sr_id;
			}
			set
			{
				if ((this._sr_id != value))
				{
					if (this._Software_Requirement.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsr_idChanging(value);
					this.SendPropertyChanging();
					this._sr_id = value;
					this.SendPropertyChanged("sr_id");
					this.Onsr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="DateTime NOT NULL")]
		public System.DateTime createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this.OncreateddateChanging(value);
					this.SendPropertyChanging();
					this._createddate = value;
					this.SendPropertyChanged("createddate");
					this.OncreateddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Software_Requirement_Package_Software", Storage="_Software_Requirement", ThisKey="sr_id", OtherKey="id", IsForeignKey=true)]
		public Software_Requirement Software_Requirement
		{
			get
			{
				return this._Software_Requirement.Entity;
			}
			set
			{
				Software_Requirement previousValue = this._Software_Requirement.Entity;
				if (((previousValue != value) 
							|| (this._Software_Requirement.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Software_Requirement.Entity = null;
						previousValue.Package_Softwares.Remove(this);
					}
					this._Software_Requirement.Entity = value;
					if ((value != null))
					{
						value.Package_Softwares.Add(this);
						this._sr_id = value.id;
					}
					else
					{
						this._sr_id = default(int);
					}
					this.SendPropertyChanged("Software_Requirement");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Work_Package_Package_Software", Storage="_Work_Package", ThisKey="wp_id", OtherKey="id", IsForeignKey=true)]
		public Work_Package Work_Package
		{
			get
			{
				return this._Work_Package.Entity;
			}
			set
			{
				Work_Package previousValue = this._Work_Package.Entity;
				if (((previousValue != value) 
							|| (this._Work_Package.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Work_Package.Entity = null;
						previousValue.Package_Softwares.Remove(this);
					}
					this._Work_Package.Entity = value;
					if ((value != null))
					{
						value.Package_Softwares.Add(this);
						this._wp_id = value.id;
					}
					else
					{
						this._wp_id = default(int);
					}
					this.SendPropertyChanged("Work_Package");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Software_Requirement")]
	public partial class Software_Requirement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _title;
		
		private System.DateTime _createddate;
		
		private string _platform;
		
		private string _description;
		
		private EntitySet<Package_Software> _Package_Softwares;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncreateddateChanging(System.DateTime value);
    partial void OncreateddateChanged();
    partial void OnplatformChanging(string value);
    partial void OnplatformChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public Software_Requirement()
		{
			this._Package_Softwares = new EntitySet<Package_Software>(new Action<Package_Software>(this.attach_Package_Softwares), new Action<Package_Software>(this.detach_Package_Softwares));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="DateTime NOT NULL")]
		public System.DateTime createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this.OncreateddateChanging(value);
					this.SendPropertyChanging();
					this._createddate = value;
					this.SendPropertyChanged("createddate");
					this.OncreateddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this.OnplatformChanging(value);
					this.SendPropertyChanging();
					this._platform = value;
					this.SendPropertyChanged("platform");
					this.OnplatformChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Software_Requirement_Package_Software", Storage="_Package_Softwares", ThisKey="id", OtherKey="sr_id")]
		public EntitySet<Package_Software> Package_Softwares
		{
			get
			{
				return this._Package_Softwares;
			}
			set
			{
				this._Package_Softwares.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Package_Softwares(Package_Software entity)
		{
			this.SendPropertyChanging();
			entity.Software_Requirement = this;
		}
		
		private void detach_Package_Softwares(Package_Software entity)
		{
			this.SendPropertyChanging();
			entity.Software_Requirement = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Work_Package")]
	public partial class Work_Package : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private int _task_id;
		
		private short _status;
		
		private string _description;
		
		private string _notes;
		
		private int _workorder;
		
		private System.DateTime _createddate;
		
		private EntitySet<Package_Software> _Package_Softwares;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Ontask_idChanging(int value);
    partial void Ontask_idChanged();
    partial void OnstatusChanging(short value);
    partial void OnstatusChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    partial void OnworkorderChanging(int value);
    partial void OnworkorderChanged();
    partial void OncreateddateChanging(System.DateTime value);
    partial void OncreateddateChanged();
    #endregion
		
		public Work_Package()
		{
			this._Package_Softwares = new EntitySet<Package_Software>(new Action<Package_Software>(this.attach_Package_Softwares), new Action<Package_Software>(this.detach_Package_Softwares));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_id", DbType="Int NOT NULL")]
		public int task_id
		{
			get
			{
				return this._task_id;
			}
			set
			{
				if ((this._task_id != value))
				{
					this.Ontask_idChanging(value);
					this.SendPropertyChanging();
					this._task_id = value;
					this.SendPropertyChanged("task_id");
					this.Ontask_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt NOT NULL")]
		public short status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(255)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workorder", DbType="Int NOT NULL")]
		public int workorder
		{
			get
			{
				return this._workorder;
			}
			set
			{
				if ((this._workorder != value))
				{
					this.OnworkorderChanging(value);
					this.SendPropertyChanging();
					this._workorder = value;
					this.SendPropertyChanged("workorder");
					this.OnworkorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="DateTime NOT NULL")]
		public System.DateTime createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this.OncreateddateChanging(value);
					this.SendPropertyChanging();
					this._createddate = value;
					this.SendPropertyChanged("createddate");
					this.OncreateddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Work_Package_Package_Software", Storage="_Package_Softwares", ThisKey="id", OtherKey="wp_id")]
		public EntitySet<Package_Software> Package_Softwares
		{
			get
			{
				return this._Package_Softwares;
			}
			set
			{
				this._Package_Softwares.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Package_Softwares(Package_Software entity)
		{
			this.SendPropertyChanging();
			entity.Work_Package = this;
		}
		
		private void detach_Package_Softwares(Package_Software entity)
		{
			this.SendPropertyChanging();
			entity.Work_Package = null;
		}
	}
	
	public partial class SelectedPakcagesResult
	{
		
		private int _id;
		
		private string _title;
		
		private System.DateTime _createddate;
		
		private string _platform;
		
		private string _description;
		
		private System.Nullable<bool> _selected;
		
		public SelectedPakcagesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="DateTime NOT NULL")]
		public System.DateTime createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this._createddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_platform", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string platform
		{
			get
			{
				return this._platform;
			}
			set
			{
				if ((this._platform != value))
				{
					this._platform = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selected", DbType="Bit")]
		public System.Nullable<bool> selected
		{
			get
			{
				return this._selected;
			}
			set
			{
				if ((this._selected != value))
				{
					this._selected = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
